### ISSUE TITLE
Compare vgg and resnet, What is your opinion?

### ISSUE THREAD

**Issue by leetesua** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#11]
Although resnet performs better than vggnet in many other projects, It seems that in vggnet is performing better in object detection than resnet, according to my experiments result. I am not sure that is the case for most people. Some of my friends have the same feelings. What is your opinion?

**Comment by yangJirui** [comment]
I think ResNet will perform better, as vgg only perform about 70% mAP according the Faster-RCNN paper.
 But i haven't tried before, but you can "pull request" to add some "VGG experiments", we are so welcome.
