### ISSUE TITLE
无法正确推导

### ISSUE THREAD

**Issue by jplnasa5** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#12]
为什么预训练模型和我自己训练出来的模型进行推导有很多密密麻麻小标注框？是IOU的阈值需要修改吗？

**Comment by yangxue0827** [comment]
我提供的训练好的模型也是这样吗？请贴上一张结果图方便我查找原因。 @jplnasa5

**Comment by yangxue0827** [comment]
另外，你用的是自己的数据集？ @jplnasa5

**Comment by jplnasa5** [comment]
对的，下图是利用训练好的resnet50模型推导效果：
![009806](https://user-images.githubusercontent.com/15087326/45143023-a2692c80-b1ec-11e8-9340-c1046e1caa7e.jpg)
我用自己的数据集训练也是同样的问题。

另外我下载你的resent101模型解压缩后只有一个checkpoint文件是怎么回事？

**Comment by yangxue0827** [comment]
感觉你没有正确加载我的权重。 @jplnasa5

**Comment by yangxue0827** [comment]
一个是resnet预训练权重，一个是我训练好的。

**Comment by jplnasa5** [comment]
我知道不能正确加载你的模型原因了。
但是现在推导出来的标注框还是有很多，请问哪里可以设置当置信度大于某个值时，标注框才能在图片显示？
另外有模块可以计算mAP吗？

**Comment by jplnasa5** [comment]
我现在重新训练的时候遇到这个问题：
tensorflow/stream_executor/cuda/cuda_dnn.cc:444] could not convert BatchDescriptor {count: 0 feature_map_count: 2048 spatial: 7 7  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX} to cudnn tensor descriptor: CUDNN_STATUS_BAD_PARAM
Aborted (core dumped)

你有遇到过吗？

**Comment by summerrr** [comment]
为什么我使用eval的时候如果把置信度置为0就满图都是方框，使用0.5就正常的结果。。。

**Comment by summerrr** [comment]
![tim 20180925143213](https://user-images.githubusercontent.com/21071386/45996730-d048df00-c0cf-11e8-909f-ca3ae0c31f65.png)
还有为什么txt里的分数都是零呢

**Comment by yangxue0827** [comment]
最后显示是分数大于这个阈值的，你设为0，当然所有预测框都会显示。 @summerrr

**Comment by summerrr** [comment]
我看你前边回答的说是置为0。。。我就很疑惑。。。

**Comment by yangxue0827** [comment]
计算mAP需要输出所有预测框，因为mAP代表的是P-R曲线的面积，所以阈值要设为0。如果只是想画图看，或者计算F1值，就需要设置阈值。 @summerrr

**Comment by summerrr** [comment]
哦哦，知道了。谢谢！
