### ISSUE TITLE
关于dota数据集

### ISSUE THREAD

**Issue by summerrr** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#14]
看到你用到了DOTA数据集，想问下对这个数据集你是怎么处理的？把它也变成了xml文件？那文件的格式是什么样子的呢？

**Comment by yangxue0827** [comment]
readme里写了，也提供了处理代码 @summerrr

**Comment by summerrr** [comment]
我没有看到有关于dota的，因为这个比较特殊，给的是四个边角的坐标，而且你程序中选择数据集时没有这个，处理好像也都是针对xmin xmax ymin ymax的，所以想问问有没有相关实现。 在2018年09月27日 14:55 ，yangxue写道： readme里写了，也提供了处理代码 @summerrr — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yangxue0827** [comment]
你来错地方了，这里是faster rcnn，是水平检测，你要去另一个repo看 @summerrr

**Comment by yangxue0827** [comment]
https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow.git @summerrr

**Comment by summerrr** [comment]
哦哦，抱歉，刚开始接触，我以为都可以呢
