### ISSUE TITLE
关于resnet提取特征

### ISSUE THREAD

**Issue by summerrr** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#15]
我看你的代码中关于采用resnet提取特征的，发现特征图是从conv_4之后那个进入roi pooling的，为什么不是从最后得到的特征图进入roi pooling呢，是采用的Object Detection Networks on Convolutional Feature Maps中NoC的方法吗？不知道我理解的对不对
![s a kkqxy9 rn57alrw43](https://user-images.githubusercontent.com/21071386/47356956-122d6b00-d6f8-11e8-9ed5-c6bf989e7ea6.png)

**Comment by yangJirui** [comment]
没错，是NoC方法。采用resNet作为backbone的话，一般都用conv_5作为head对每个roi进行分类和回归。 @summerrr
