### ISSUE TITLE
关于resnet的结构

### ISSUE THREAD

**Issue by summerrr** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#16]
![image](https://user-images.githubusercontent.com/21071386/48708382-6830f800-ec3d-11e8-806d-8c141ea9b9df.png)
想问下resnet.py为什么这里block3的stride=1呢，正常的resnet不应该是stride=2呢，这里设为1是有什么原因嘛？

**Comment by yangxue0827** [comment]
tf.slim对resnet的实现方式和论文有一点不样。 @summerrr
