### ISSUE TITLE
Training problem with ohem

### ISSUE THREAD

**Issue by Ixiaohuihuihui** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#20]
When I training with ohem, some error has occurred:
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[2000,7,7,512]

**Comment by yangxue0827** [comment]
out of memory @Ixiaohuihuihui

**Comment by Ixiaohuihuihui** [comment]
> out of memory @Ixiaohuihuihui

But I have 4 nvidia gpu, they are all free of memory.

**Comment by yangxue0827** [comment]
This code only supports single gpu training. If tensorflow wants to use multiple GPUs, you need to write multi-GPU training code instead of simply setting up multi-GPU training. @Ixiaohuihuihui

**Comment by Ixiaohuihuihui** [comment]
actually, I only assign single gpu to train...

**Comment by chaojixiaohaizei** [comment]
@yangxue0827 ,您好，博主，如何用ohem训练，是直接运行train.oy吗

**Comment by Ixiaohuihuihui** [comment]
@chaojixiaohaizei refer [here](https://github.com/DetectionTeamUCAS/Faster-RCNN_Tensorflow/blob/db355dc5e22f7e4f3106038e5e621d04df64c876/libs/configs/cfgs.py#L153)
