### ISSUE TITLE
How to use 

### ISSUE THREAD

**Issue by zhang295498** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#29]

**Comment by yangxue0827** [comment]
Please read README.md. @zhang295498

**Comment by zhang295498** [comment]
what i mean is that how to use it to eval the mAP of this model. and what does it require?

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/59761000-3b71bb80-92c6-11e9-9e78-073f81addd6f.png)
