### ISSUE TITLE
inference问题

### ISSUE THREAD

**Issue by leishi2018** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#3]
楼主运行inference.py程序时会出现

**Comment by leishi2018** [comment]
ImportError: dynamic module does not define module export function (PyInit_cython_bbox)

**Comment by yangxue0827** [comment]
cd $PATH_ROOT/libs/box_utils/cython_utils
python setup.py build_ext --inplace
@leishi2018

**Comment by leishi2018** [comment]
thanks,it work.@yangxue0827
