### ISSUE TITLE
Does the roi_pooling func is roi align ? 

### ISSUE THREAD

**Issue by zhao34731** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#31]
Hello my friend , I am using your Faster RCNN Code for my research . In the code, the Roi Pooling is used to pooling the different features maps to united spatial size. Here the tf.image.crop_and_resize function uses bilinear method to get the cropped feature. And the Roi Align method also use the bilinear method. I wonder whether the method in your code roi_pooling function is the same as Roi Align ? thank you

**Comment by yangxue0827** [comment]
Can be seen as RoI Align
@zhao34731
