### ISSUE TITLE
运行inference.py,调用与训练模型，检测框和目标名混乱

### ISSUE THREAD

**Issue by cmstudyscode** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#34]
![004545](https://user-images.githubusercontent.com/43026059/69774227-4bc08780-11d0-11ea-814b-fd2d6c3828ca.jpg)

**Comment by yangxue0827** [comment]
检查一下你是否加载了权重，你这效果看起来是加载的预训练权重。注意训练好的权重路径是：output/trained_weights/你下载的文件夹/四个权重文件
@cmstudyscode
