### ISSUE TITLE
NMS about postfastrcnn

### ISSUE THREAD

**Issue by zhao34731** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#37]
Hello, my friend, 
I'm very interested in your implementations for several excellent object detection algorithms.  When I read your python file, 'build_whole_network.py' , the  function 

'keep = tf.image.non_max_suppression(
                    boxes=tmp_decoded_boxes,
                    scores=tmp_score,
                    max_output_size=cfgs.FAST_RCNN_NMS_MAX_BOXES_PER_CLASS,
                    iou_threshold=cfgs.FAST_RCNN_NMS_IOU_THRESHOLD). 
calculate the indices after NMS. It's ok. But a question might confused me. 

In the function 'tf.image.non_max_suppression', the official documents define the boxes, the coordinate vales are [ymin, xmin, ymax, xmax], However, in your code, the order of tmp_decoded_boxes is [xmin, ymin, xmax, ymax].
 
'def clip_boxes_to_img_boundaries(decode_boxes, img_shape):
    '''

    :param decode_boxes:
    :return: decode boxes, and already clip to boundaries
    '''

    with tf.name_scope('clip_boxes_to_img_boundaries'):

        # xmin, ymin, xmax, ymax = tf.unstack(decode_boxes, axis=1)
        xmin = decode_boxes[:, 0]
        ymin = decode_boxes[:, 1]
        xmax = decode_boxes[:, 2]
        ymax = decode_boxes[:, 3]
        img_h, img_w = img_shape[1], img_shape[2]

        img_h, img_w = tf.cast(img_h, tf.float32), tf.cast(img_w, tf.float32)

        xmin = tf.maximum(tf.minimum(xmin, img_w-1.), 0.)
        ymin = tf.maximum(tf.minimum(ymin, img_h-1.), 0.)

        xmax = tf.maximum(tf.minimum(xmax, img_w-1.), 0.)
        ymax = tf.maximum(tf.minimum(ymax, img_h-1.), 0.)

        return tf.transpose(tf.stack([xmin, ymin, xmax, ymax]))' in your code 

Does it ok for calculating NMS  indices when using [xmin, ymin, xmax, ymax], thank you !

Besides, do you plan to write a soft-NMS function with TF.

**Comment by yangxue0827** [comment]
The order of xy does not affect the results. Softnms should have many implementations on the web that you can use directly. @zhao34731
