### ISSUE TITLE
_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)

### ISSUE THREAD

**Issue by leetesua** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#7]
![image](https://user-images.githubusercontent.com/25045281/42815015-98527b82-89f8-11e8-9e06-d9c39f78dee8.png)

**Comment by leetesua** [comment]
我在用原始的VOCdevkit数据集做训练时发生这个错误。

**Comment by leetesua** [comment]
I got an error when training the original VOCdevkit dataset using this model. It runs demo perfectly before this.

**Comment by yangxue0827** [comment]
something wrong with your tfrecord @leetesua

**Comment by leetesua** [comment]
@yangxue0827 Thank you for your reminder, I have solved my issue. Now everything works good with this model. Really appreciated! 

what's behind it is, the order of loading xml file (in convert_data_to_tfrecord.py) matters,  because my dataset includes both pascal voc 2007 and  2012, however the order of coordinates in bndbox in xml is different between 2007 and 2012,
