### ISSUE TITLE
About anchor centers  

### ISSUE THREAD

**Issue by mensaochun** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#8]
In function make_anchors(), there are code:
` x_centers = tf.range(featuremap_width, dtype=tf.float32) * stride
 y_centers = tf.range(featuremap_height, dtype=tf.float32) * stride`
It make me confusing.
As the code do, if stride is 32, the x_centers and y_centers may be like 0,32,64,96...
To my opinion, x_centers and y_centers should be 16, 48, 80,112..., if so, x y will be center.
Am I understanding right?

**Comment by yangxue0827** [comment]
You're right. We tried two forms, and the results showed that it didn't affect the results a lot. @mensaochun
