### ISSUE TITLE
PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue

### ISSUE THREAD

**Issue by leetesua** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#9]
PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
![image](https://user-images.githubusercontent.com/25045281/42935411-248ccd62-8b7c-11e8-86ae-4ae254db051d.png)
![image](https://user-images.githubusercontent.com/25045281/42935631-b35bca98-8b7c-11e8-8932-1587e64f37af.png)
I was training with my own data, which has two categories. I got several steps of successfully training, with all the loss looks good, then I got an error  like this.

**Comment by leetesua** [comment]
![image](https://user-images.githubusercontent.com/25045281/42935868-5760d868-8b7d-11e8-962c-eece27c0b17b.png)

this is my xml file. I am not sure if this helps. I trained with 65 images (i just want to run through the model first), does this

**Comment by leetesua** [comment]
I got the printed fast_rcnn_loc_loss to be 0.0 several times, does this mean anything? I didn't have this when training pascal VOC dataset

**Comment by yangxue0827** [comment]
@leetesua  https://github.com/yangxue0827/FPN_Tensorflow/blob/master/sample.xml

**Comment by yangxue0827** [comment]
It is normal phenomenon that fast rcnn loc loss is 0 at begin. @leetesua

**Comment by FannierPeng** [comment]
@leetesua Have you solved this problem? I found the image that caused the error by Binary Search method, and deleted  it and its corresponding xml, then the error disappeared.

**Comment by Yansslc** [comment]
I have met same problem while trainning. I found that there are no target objects in some images, so I just deleted those images and the error diappeared.

**Comment by Yansslc** [comment]
I have met same problem while trainning. I found that there are no target objects in some images, so I just deleted those images and the error diappeared. @leetesua
